### ISSUE TITLE
build fails (due to missing resources?)

### ISSUE THREAD

**Issue by IzzySoft** [tahaak67/Farhan#75]
Trying to build v0.2.2 fails at `:core:verifyReleaseResources`:

```
Execution failed for task ':core:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/usage_widget_preview.xml:25: AAPT: error: attribute layout_constraintTop_toTopOf (aka ly.com.tahaben.core:layout_constraintTop_toTopOf) not found.

     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/usage_widget_preview.xml:25: AAPT: error: attribute layout_constraintStart_toStartOf (aka ly.com.tahaben.core:layout_constraintStart_toStartOf) not found.

     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/usage_widget_preview.xml:34: AAPT: error: attribute layout_constraintTop_toBottomOf (aka ly.com.tahaben.core:layout_constraintTop_toBottomOf) not found.

     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/usage_widget_preview.xml:51: AAPT: error: attribute layout_constraintStart_toStartOf (aka ly.com.tahaben.core:layout_constraintStart_toStartOf) not found.

     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/usage_widget_preview.xml:51: AAPT: error: attribute layout_constraintTop_toBottomOf (aka ly.com.tahaben.core:layout_constraintTop_toBottomOf) not found.

     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/usage_widget_preview.xml:61: AAPT: error: attribute layout_constraintTop_toTopOf (aka ly.com.tahaben.core:layout_constraintTop_toTopOf) not found.

     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/usage_widget_preview.xml:61: AAPT: error: attribute layout_constraintStart_toEndOf (aka ly.com.tahaben.core:layout_constraintStart_toEndOf) not found.

     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/usage_widget_preview.xml:76: AAPT: error: attribute layout_constraintStart_toStartOf (aka ly.com.tahaben.core:layout_constraintStart_toStartOf) not found.

     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/usage_widget_preview.xml:76: AAPT: error: attribute layout_constraintTop_toBottomOf (aka ly.com.tahaben.core:layout_constraintTop_toBottomOf) not found.

     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/usage_widget_preview.xml:86: AAPT: error: attribute layout_constraintTop_toTopOf (aka ly.com.tahaben.core:layout_constraintTop_toTopOf) not found.

     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/usage_widget_preview.xml:86: AAPT: error: attribute layout_constraintStart_toEndOf (aka
```

Could it be something was not checked in to this repo?

**Comment by IzzySoft** [comment]
@tahaak67 could you please take a look? ^^ (guess you've missed the notification for this)

**Comment by tahaak67** [comment]
I'll take a look later tonight

**Comment by tahaak67** [comment]
Ok so i just looked through the files and everything seems to be there.
i also cloned the project again and tried running it and building a signed apk and everything was successful, from what branch are you tring to build? if its the main branch can you please pull and try again?

**Comment by IzzySoft** [comment]
> from what branch are you tring to build?

From the commit the tag points to: 876c925dc0ec76d7073d5ca5d1bd8b9f7c1c49e6

> if its the main branch can you please pull and try again?

I can of course. Though it would be strange if that suddenly would work out. If the resources were missing at that commit, how should they suddenly show up? But then, strange things happen (non-deterministic builds), so let's see… Nope, as expected, error remains.

**Comment by tahaak67** [comment]
ok so i took a deeper look and it seems the file `usage_widget_preview.xml` has some constriant layout attributes (i don't use constraint layout) so i removed thoes attributes and also fixed some missing dependencies in the end2end test, the changes are at [1f5f1cf](https://github.com/tahaak67/Farhan/commit/1f5f1cf8c6fae055354f1654b2eb61564c16e9be) please pull from main and try again

**Comment by IzzySoft** [comment]
Thanks, now it builds! As the background of my question are [Reproducible Builds](https://reproducible-builds.org/) (see [Reproducible Builds, special client support and more at IzzyOnDroid](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)), could you provide me an APK you've built and signed from the same commit to compare against – so we can see if we can establish RB for your next release, or what might need adjustment? Thanks in advance!

**Comment by tahaak67** [comment]
[app-release.zip](https://github.com/user-attachments/files/18100639/app-release.zip)
here you go, i had to put it in a zip file because github doesn't allow .apk here

**Comment by IzzySoft** [comment]
> i had to put it in a zip file because github doesn't allow .apk here

It's MS, so it just goes by file extensions. Simply rename it to `*.zip` and suddenly it's fine :man_shrugging: But never mind, works this way as well.

But it's not RB. Here's the diff:

```diff
  -rw----     0.0 fat      772 b-      421 defN 1981-01-01 01:01:02 6d825b66 res/Ac.xml
- -rw----     0.0 fat   353464 b-   172527 defN 1981-01-01 01:01:02 f217fdc2 res/Ad.ttf
+ -rw----     0.0 fat   353464 b-   172531 defN 1981-01-01 01:01:02 f217fdc2 res/Ad.ttf
  -rw----     0.0 fat      465 b-      465 stor 1981-01-01 01:01:02 f842e86c res/Ag.png
  -rw----     0.0 fat      468 b-      254 defN 1981-01-01 01:01:02 57f93ac7 res/Ag.xml
  -rw----     0.0 fat      524 b-      258 defN 1981-01-01 01:01:02 553fdc4c res/Am.xml
@@ -1099,7 +1099,7 @@
  -rw----     0.0 fat      740 b-      382 defN 1981-01-01 01:01:02 b331980d res/a7.xml
  -rw----     0.0 fat     1888 b-      510 defN 1981-01-01 01:01:02 e6046057 res/a71.xml
  -rw----     0.0 fat      860 b-      294 defN 1981-01-01 01:01:02 c29e639b res/a8.xml
- -rw----     0.0 fat    11371 b-    11371 stor 1981-01-01 01:01:02 3c2fbab2 res/aA.png
+ -rw----     0.0 fat    11370 b-    11370 stor 1981-01-01 01:01:02 11f88134 res/aA.png
  -rw----     0.0 fat      700 b-      302 defN 1981-01-01 01:01:02 26ae1ab3 res/aD.xml
```

`Ad.ttf` is strange: it's identical when uncompressed (previous to last column: file hash), but the compressed size differs by a few bytes. That smells a bit like `zlib-ng` was used instead of `zlib`, but that cannot be as then all other files would be affected as well (tested: confirmed, it's not that). Still, I cannot even get the compression level of the file via `zipfile`. Not sure what happened to that font.

The PNG on the other side also differs when uncompressed. Could it be you use PNGCrunch or something like that? Those tools produce non-deterministic results. If so, for this I would have a hint. But if we cannot resolve the TTF file, that won't help much…

Do you have any ideas there? Maybe let's compare build environments: I've built the APK on Debian bookworm using JDK-17 and gradle at the command line. What did you use?

**Comment by tahaak67** [comment]
> It's MS, so it just goes by file extensions. Simply rename it to `*.zip` and suddenly it's fine 🤷‍♂️ But never mind, works this way as well.

aha, thanks for the info.

> Do you have any ideas there? Maybe let's compare build environments:

I'll let you know if i have any ideas just kind of in a rush at the moment 😅
I built it with Android Studio 2024.2.1 Patch 3 using the "Generate signed app bundle / APK" tool and i have jbr-17.0.9 (jetbrains runtime) set as the JDK.

**Comment by IzzySoft** [comment]
> Generate signed app bundle / APK

Ouch. Not sure, but if that creates the APK from the bundle (which I'm afraid it does), that could be the culprit: those APKs are not RB. Is there an option to (first clean and then) only create the APK?

> jbr-17.0.9 (jetbrains runtime)

that could also be an issue. if possible, can you select OpenJDK 17 instead? I know the option exists, but it could be you'd first need to download & install it (which AFAIK is possible from within Studio).

**Comment by tahaak67** [comment]
<img width="654" alt="Screenshot 2024-12-13 at 10 15 09 AM" src="https://github.com/user-attachments/assets/1475bc43-e1f1-423f-9a39-9148e19ac10e" />

the tools gives an options between a bundle and an apk, i haven't investigated so not sure i always use the apk options to share here on github and its universal so works on all devices

here is the signed apk with open jdk17, changed the file extension this time 🙂

[app-release.zip](https://github.com/user-attachments/files/18123564/app-release.zip)

**Comment by IzzySoft** [comment]
Same still:

```diff
  -rw----     0.0 fat      772 b-      421 defN 1981-01-01 01:01:02 6d825b66 res/Ac.xml
- -rw----     0.0 fat   353464 b-   172527 defN 1981-01-01 01:01:02 f217fdc2 res/Ad.ttf
+ -rw----     0.0 fat   353464 b-   172531 defN 1981-01-01 01:01:02 f217fdc2 res/Ad.ttf
  -rw----     0.0 fat      465 b-      465 stor 1981-01-01 01:01:02 f842e86c res/Ag.png
  -rw----     0.0 fat      468 b-      254 defN 1981-01-01 01:01:02 57f93ac7 res/Ag.xml
  -rw----     0.0 fat      524 b-      258 defN 1981-01-01 01:01:02 553fdc4c res/Am.xml
@@ -1099,7 +1099,7 @@
  -rw----     0.0 fat      740 b-      382 defN 1981-01-01 01:01:02 b331980d res/a7.xml
  -rw----     0.0 fat     1888 b-      510 defN 1981-01-01 01:01:02 e6046057 res/a71.xml
  -rw----     0.0 fat      860 b-      294 defN 1981-01-01 01:01:02 c29e639b res/a8.xml
- -rw----     0.0 fat    11371 b-    11371 stor 1981-01-01 01:01:02 3c2fbab2 res/aA.png
+ -rw----     0.0 fat    11370 b-    11370 stor 1981-01-01 01:01:02 11f88134 res/aA.png
  -rw----     0.0 fat      700 b-      302 defN 1981-01-01 01:01:02 26ae1ab3 res/aD.xml
```

As for the PNG; those are different files, so for this it doesn't matter what JDK is being used. That TTF still confuses me, being identical when uncompressed but differs in compression by 4 bytes. And I cannot determine its compression level even in your APK:

```
$ list-compression-levels *upstream.apk res/Ad.ttf
Traceback (most recent call last):
  File "/mnt/data/src/git/forks/obfusk/reproducible-apk-tools/list-compresslevel.py", line 144, in <module>
    list_compresslevel(args.apk, *args.patterns, levels=clevels)
  File "/mnt/data/src/git/forks/obfusk/reproducible-apk-tools/list-compresslevel.py", line 52, in list_compresslevel
    raise Error(f"Unable to determine compresslevel for {info.filename!r}")
__main__.Error: Unable to determine compresslevel for 'res/Ad.ttf'

$ list-compression-levels *unsigned.apk res/Ad.ttf
filename='res/Ad.ttf' compresslevel=9
```

("upstream" is yours, "unsigned" the one my builder produced). Guess if we cannot solve that one, trying to fix the PNG is moot (for RB at least, as we cannot reach RB if that remains different). I have no idea how to control the compression level with gradle (except that I know you can use `aaptoptions` to specify `noCompress` for file extensions you name) – so I'm rather out of ideas there. What OS are you building on? And would using e.g. Github workflows be an option for you? Of course we can gladly offer you using our "RB tooling": `rbtlog` can also be used to "just build, don't compare". It supports Podman and Docker containers for building (using "ephemeral" containers ensures you always have a clean build environment).

**Comment by IzzySoft** [comment]
>> jbr-17.0.9 (jetbrains runtime)

> that could also be an issue. if possible, can you select OpenJDK 17 instead? I know the option exists, but it could be you'd first need to download & install it (which AFAIK is possible from within Studio).

We just had the very same issues with another app, also using Jetbrains. Have you switched to OpenJDK meanwhile?

**Comment by IzzySoft** [comment]
@tahaak67 any word?

**Comment by tahaak67** [comment]
@IzzySoft hey the last apk i uploaded in the comment was built using jdk 17.
I'll look into using a github workflow for releases. But meanwhile should i worry about uploading the next release manually like before? Will that effect the listing on izzy?

**Comment by IzzySoft** [comment]
> hey the last apk i uploaded in the comment was built using jdk 17.

Which one? OpenJDK – or Jetbrains?

> Will that effect the listing on izzy?

Our updater just picks what's at the release, scans it, and (if all seems fine) publishes it – it does not check for RB. The latter is done by our builders, on a separate track. So a failed RB does not stop your (maybe urgent security) update from going live, it just keeps the "green shield" from coming up. Later, (some) clients might offer an option to only install/update confirmed RBs, so the choice is with the people (as it should be).

Btw: My guess for that PNG is that it is rendered from `res/mipmap-anydpi-v26/ic_launcher.xml`; that should be easy to avoid by "forbidding" such action:

```gradle
android {
    // disable generating PNGs from vector drawables:
    defaultConfig {
        vectorDrawables.generatedDensities = []
    }
}
```

For the TTF, I have no clue. That's definitely a compression issue (same uncompressed size, same file hash – just different compressed size), no idea what causes that. What OS are you building on?

**Comment by tahaak67** [comment]
> 
> Which one? OpenJDK – or Jetbrains?
> 

Open JDK 17


> What OS are you building on?

Mac os 15.2

**Comment by IzzySoft** [comment]
Thanks, no issues known to this combination. Still wondering what causes that compression difference (and the unknown compression level) for that TTF. Especially as I cannot find a TTF in your repo here. Must be pulled by Compose, due to your defining that CairoFont I guess (the TTF mentions it's Cairo). But no idea how to approach that; I'm no Android dev…

**Comment by tahaak67** [comment]
Id do have the ttf file for the cairo font i use its here: https://github.com/tahaak67/Farhan/tree/main/core%2Fsrc%2Fmain%2Fres%2Ffont

**Comment by IzzySoft** [comment]
Ah! Funny that my search didn't surface it. And it still doesn't answer how the compression difference comes to happen. Maybe we try to simply turn off compression for TTF? I mean, it's just 150kB difference. And we'd know your app is RB then afterwards.

```gradle
aaptOptions {
    noCompress 'ttf', '.ttf'
}
```

(found in [this SO post](https://stackoverflow.com/a/27041710/2533433)). If you want to dig in deeper into the compression stuff, there's [a mail at RB.org on the topic](https://lists.reproducible-builds.org/pipermail/rb-general/2024-September/003526.html) 😉

**Comment by IzzySoft** [comment]
@tahaak67 any chance to give this a try?

**Comment by tahaak67** [comment]
I merged some changes to main, here is the built apk from the main branch, with compression for 'ttf' turned off and disabling generating png from vectors.
[app-release.zip](https://github.com/user-attachments/files/19409283/app-release.zip)

hopfully this works 🤲 :)

**Comment by IzzySoft** [comment]
Sorry, but unfortunately does not even build:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':core:verifyReleaseResources'.
> A failure occurred while executing com.android.build.gradle.tasks.VerifyLibraryResourcesTask$Action
   > Android resource linking failed
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:19: AAPT: error: resource style/TextAppearance.AppCompat.Large (aka ly.com.tahaben.core:style/TextAppearance.AppCompat.Large) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:19: AAPT: error: attribute layout_constraintTop_toTopOf (aka ly.com.tahaben.core:layout_constraintTop_toTopOf) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:19: AAPT: error: attribute layout_constraintStart_toStartOf (aka ly.com.tahaben.core:layout_constraintStart_toStartOf) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:30: AAPT: error: resource style/TextAppearance.AppCompat.Medium (aka ly.com.tahaben.core:style/TextAppearance.AppCompat.Medium) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:30: AAPT: error: attribute layout_constraintStart_toStartOf (aka ly.com.tahaben.core:layout_constraintStart_toStartOf) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:30: AAPT: error: attribute layout_constraintEnd_toEndOf (aka ly.com.tahaben.core:layout_constraintEnd_toEndOf) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:30: AAPT: error: attribute layout_constraintTop_toBottomOf (aka ly.com.tahaben.core:layout_constraintTop_toBottomOf) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:45: AAPT: error: attribute layout_constraintTop_toBottomOf (aka ly.com.tahaben.core:layout_constraintTop_toBottomOf) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:45: AAPT: error: attribute layout_constraintStart_toStartOf (aka ly.com.tahaben.core:layout_constraintStart_toStartOf) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:45: AAPT: error: attribute layout_constraintEnd_toEndOf (aka ly.com.tahaben.core:layout_constraintEnd_toEndOf) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:59: AAPT: error: resource style/TextAppearance.AppCompat.Small (aka ly.com.tahaben.core:style/TextAppearance.AppCompat.Small) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:59: AAPT: error: attribute layout_constraintHorizontal_bias (aka ly.com.tahaben.core:layout_constraintHorizontal_bias) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:59: AAPT: error: attribute layout_constraintTop_toTopOf (aka ly.com.tahaben.core:layout_constraintTop_toTopOf) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:59: AAPT: error: attribute layout_constraintStart_toStartOf (aka ly.com.tahaben.core:layout_constraintStart_toStartOf) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:59: AAPT: error: attribute layout_constraintEnd_toStartOf (aka ly.com.tahaben.core:layout_constraintEnd_toStartOf) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:74: AAPT: error: attribute layout_constraintHorizontal_bias (aka ly.com.tahaben.core:layout_constraintHorizontal_bias) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:74: AAPT: error: attribute layout_constraintEnd_toStartOf (aka ly.com.tahaben.core:layout_constraintEnd_toStartOf) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:74: AAPT: error: attribute layout_constraintStart_toEndOf (aka ly.com.tahaben.core:layout_constraintStart_toEndOf) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:74: AAPT: error: attribute layout_constraintTop_toBottomOf (aka ly.com.tahaben.core:layout_constraintTop_toBottomOf) not found.
         
     ERROR: /build/repo/core/build/intermediates/merged_res/release/mergeReleaseResources/layout/timeout_dialog.xml:74: AAPT: error: resource style/TextAppearance.AppCompat.Small (aka ly.com.tahaben.core:style/TextAppearance.AppCompat.Small) not found.
```

May I suggest you to check out that commit (9119da99e6b882eacee80477daa406a1168fc826) to a separate place, and try building from there yourself? You should then be able to reproduce the error – and hopefully find and fix the culprit 😉 Thanks!

**Comment by tahaak67** [comment]
It still worked even if i clone the project to a diffirent place, anyway i deleted the 'timeout_dialog' file since its no longer used in the latest release. android studio seems to ignore it when building the project for some reason 

[app-release.zip](https://github.com/user-attachments/files/19409706/app-release.zip)

**Comment by IzzySoft** [comment]
I cannot tell about Studio; we built via gradle at the command line, in ephemeral containers (which also ensures there are no artifacts remaining from previous builds which could be accidentally reused). For Farhan, we currently use OpenJDK 15 on Debian bookworm, with this recipe:

```yaml
build:
  - git clone -b 2.2.2 https://github.com/zlib-ng/zlib-ng.git
  - pushd zlib-ng
  - _options=( -G Ninja -DCMAKE_BUILD_TYPE=None -DCMAKE_INSTALL_PREFIX=/opt -DCMAKE_INSTALL_LIBDIR=lib -Wno-dev -DWITH_GTEST=OFF -DWITH_UNALIGNED=OFF )
  - cmake -B build "${_options[@]}"
  - cmake --build build
  - cmake -B build-compat "${_options[@]}" -DZLIB_COMPAT=ON
  - cmake --build build-compat
  - cmake --install build
  - cmake --install build-compat
  - popd
  - export LD_LIBRARY_PATH=/opt/lib
  - chmod +x gradlew
  - ./gradlew assembleRelease
```

(we have to build `zlib-ng` in advance as your build seems to use that ([see above](#issuecomment-2537409681)).

And sorry to tell you: but building from the commit specified in the new APK fails here with the very same errors. Maybe you have some setting in Studio that suppresses these (or the corresponding gradle task, `:core:verifyReleaseResources`)? I mean, it's possible to do that, but whether it's wise is a different question.

    ./gradlew assembleRelease -x :core:verifyReleaseResources

skips those – but then the same show up in `:core-ui:verifyReleaseResources`. So,

    ./gradlew assembleRelease -x :core:verifyReleaseResources -x :core-ui:verifyReleaseResources

and it fails in `:infinite_scroll_blocker:infinite_scroll_blocker_data:verifyReleaseResources` with the same. I don't think that's a path we should go – would be preferable to have those ReleaseResources fixed.

**Comment by tahaak67** [comment]
i fixed all issues that arise with the verifyReleaseResources task at develop 1285a57

**Comment by IzzySoft** [comment]
Thanks! Is there an APK to it to compare against – or shall I just try whether it builds first?

**Comment by tahaak67** [comment]
oh yes here [app-release.zip](https://github.com/user-attachments/files/19410592/app-release.zip)

**Comment by IzzySoft** [comment]
Yepp, that builds – with a huge diff because of… oh, no more `zlib-ng`? Let's kick that out of the recipe then and try again…

Yeah! 🥳 Congrats, that's RB!!! Next release when? 😃

**Comment by tahaak67** [comment]
Soon 😀 (hopefully within the next three days)

**Comment by IzzySoft** [comment]
Please give me a ping then, so I cannot forget establish RB for it then 🤗

**Comment by tahaak67** [comment]
@IzzySoft new version released

**Comment by IzzySoft** [comment]
build › commit › commit › tag › attach APK built 2 commits before 🙈 OK, that can be cured by a `git reset --soft b06977bfb7e01dab3b36762f60128671cab27c3b`. But unfortunately, the build fails:

```
> Task :app:kspReleaseKotlin FAILED

> Task :app:copyRoomSchemas
e: [ksp] /build/repo/app/src/main/java/ly/com/tahaben/farhan/db/FarhanDatabase.kt:30: Schema '1.json' required for migration was not found at the schema out folder: /build/repo/app/schemas/ly.com.tahaben.farhan.db.FarhanDatabase. Cannot generate auto migrations.
```

Looks like you forgot to commit/push a file named `1.json`?

**Comment by tahaak67** [comment]
of course i did :'), they're added now.

**Comment by IzzySoft** [comment]
Good to know, thanks! That needed a bit gitty-tricky-flicky-around:

```yaml
build:
  - git checkout 8fb243715c9facf8f6ea50d10374239b6ad6e5d8
  - git reset --soft b06977bfb7e01dab3b36762f60128671cab27c3b
  - ./gradlew assembleRelease
```

(checkout the commit with the missing code, then tell git to assume it was another commit so that one gets embedded into `vcsInfo`, then build) – but… It succeeded! 🥳 So [here comes your welcome wagon](https://floss.social/@IzzyOnDroid/114256352117319092):

![Image](https://github.com/user-attachments/assets/a19541f9-a263-4a13-9a67-0e1c237a043a)

Btw, there's a lot of debug output when building, like

```
/build/repo/core-ui/build/intermediates/merged_res/release/mergeReleaseResources/values-ta/values-ta.xml:249: Multiple substitutions specified in non-positional format of string resource string/monthly_usage_report_msg_less_hrs_min. Did you mean to add the formatted="false" attribute?
```

That is definitely helpful for test builds, but maybe you want to suppress that for release builds (if that's possible; I'm no Android dev, so I'm not sure there)? Logs for a single build are around 250 kB currently. Nothing urgent, just wanted to mention it.

[ly.com.tahaben.farhan.log.gz](https://github.com/user-attachments/files/19533194/ly.com.tahaben.farhan.log.gz)

So thanks again for all your help – and for maintaining this app! 🤗
